In [10]:
#Filter Pandas Dataframe with multiple conditions 
# using loc and iloc function and using the bitwise operator(and, or , not)

# import module
import pandas as pd

# assign data
dataFrame = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 88000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'MASUS', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})

# display dataframe
print(dataFrame)
dataFrame.loc[(dataFrame["Salary"] >= 100000) & (dataFrame["Age"] <40) & dataFrame["JOB"].str.startswith("D"), ["Name", "JOB"] ]

         Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37   88000        MASUS
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

        Name       JOB
0   RACHEL    DESIGNER

In [ ]:
# so filter will be done in different mmethod 
'''
1. using loc method 
2. using the nparray with (where)
3. using query '''

In [14]:
import pandas as pd 
import numpy as np

data = {
    "name":["Ali", "Sara", "Omar", "lina", "Mona"],
    "age" :[25,32,40,29,35],
    "salary": [40000, 60000, 80000, 50000, 70000],
    "city": ["Cairo", "Alex", "Cairo", "Giza", "Alex"]
}
df = pd.DataFrame(data , index= [x for x in range(1, len(data["name"])+1)])
print(df)

   name  age  salary   city
1   Ali   25   40000  Cairo
2  Sara   32   60000   Alex
3  Omar   40   80000  Cairo
4  lina   29   50000   Giza
5  Mona   35   70000   Alex

In [ ]:
# using the loc lets work to find out 
df.loc[(df["age"] >30) & (df["salary"] >= 60000)]
#using loc is enough

   name  age  salary   city
2  Sara   32   60000   Alex
3  Omar   40   80000  Cairo
5  Mona   35   70000   Alex