In [10]:
# pivoting the table we have 
import pandas as pd 

# How to Create a Pivot Table in Python using Pandas?

# using the pivot_table() method 

help(pd.pivot_table)

Help on function pivot_table in module pandas.core.reshape.pivot:

pivot_table(
    data: 'DataFrame',
    values=None,
    index=None,
    columns=None,
    aggfunc: 'AggFuncType' = 'mean',
    fill_value=None,
    margins: 'bool' = False,
    dropna: 'bool' = True,
    margins_name: 'Hashable' = 'All',
    observed: 'bool | lib.NoDefault' = <no_default>,
    sort: 'bool' = True
) -> 'DataFrame'
    Create a spreadsheet-style pivot table as a DataFrame.

    The levels in the pivot table will be stored in MultiIndex objects
    (hierarchical indexes) on the index and columns of the result DataFrame.

    Parameters
    ----------
    data : DataFrame
    values : list-like or scalar, optional
        Column or columns to aggregate.
    index : column, Grouper, array, or list of the previous
        Keys to group by on the pivot table index. If a list is passed,
        it can contain any of the other types (except list). If an array is
        passed, it must be the same length as the data and will be used in
        the same manner as column values.
    columns : column, Grouper, array, or list of the previous
        Keys to group by on the pivot table column. If a list is passed,
        it can contain any of the other types (except list). If an array is
        passed, it must be the same length as the data and will be used in
        the same manner as column values.
    aggfunc : function, list of functions, dict, default "mean"
        If a list of functions is passed, the resulting pivot table will have
        hierarchical columns whose top level are the function names
        (inferred from the function objects themselves).
        If a dict is passed, the key is column to aggregate and the value is
        function or list of functions. If ``margin=True``, aggfunc will be
        used to calculate the partial aggregates.
    fill_value : scalar, default None
        Value to replace missing values with (in the resulting pivot table,
        after aggregation).
    margins : bool, default False
        If ``margins=True``, special ``All`` columns and rows
        will be added with partial group aggregates across the categories
        on the rows and columns.
    dropna : bool, default True
        Do not include columns whose entries are all NaN. If True,
        rows with a NaN value in any column will be omitted before
        computing margins.
    margins_name : str, default 'All'
        Name of the row / column that will contain the totals
        when margins is True.
    observed : bool, default False
        This only applies if any of the groupers are Categoricals.
        If True: only show observed values for categorical groupers.
        If False: show all values for categorical groupers.

        .. deprecated:: 2.2.0

            The default value of ``False`` is deprecated and will change to
            ``True`` in a future version of pandas.

    sort : bool, default True
        Specifies if the result should be sorted.

        .. versionadded:: 1.3.0

    Returns
    -------
    DataFrame
        An Excel style pivot table.

    See Also
    --------
    DataFrame.pivot : Pivot without aggregation that can handle
        non-numeric data.
    DataFrame.melt: Unpivot a DataFrame from wide to long format,
        optionally leaving identifiers set.
    wide_to_long : Wide panel to long format. Less flexible but more
        user-friendly than melt.

    Notes
    -----
    Reference :ref:`the user guide <reshaping.pivot>` for more examples.

    Examples
    --------
    >>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
    ...                          "bar", "bar", "bar", "bar"],
    ...                    "B": ["one", "one", "one", "two", "two",
    ...                          "one", "one", "two", "two"],
    ...                    "C": ["small", "large", "large", "small",
    ...                          "small", "large", "small", "small",
    ...                          "large"],
    ...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    ...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})
    >>> df
         A    B      C  D  E
    0  foo  one  small  1  2
    1  foo  one  large  2  4
    2  foo  one  large  2  5
    3  foo  two  small  3  5
    4  foo  two  small  3  6
    5  bar  one  large  4  6
    6  bar  one  small  5  8
    7  bar  two  small  6  9
    8  bar  two  large  7  9

    This first example aggregates values by taking the sum.

    >>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
    ...                        columns=['C'], aggfunc="sum")
    >>> table
    C        large  small
    A   B
    bar one    4.0    5.0
        two    7.0    6.0
    foo one    4.0    1.0
        two    NaN    6.0

    We can also fill missing values using the `fill_value` parameter.

    >>> table = pd.pivot_table(df, values='D', index=['A', 'B'],
    ...                        columns=['C'], aggfunc="sum", fill_value=0)
    >>> table
    C        large  small
    A   B
    bar one      4      5
        two      7      6
    foo one      4      1
        two      0      6

    The next example aggregates by taking the mean across multiple columns.

    >>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
    ...                        aggfunc={'D': "mean", 'E': "mean"})
    >>> table
                    D         E
    A   C
    bar large  5.500000  7.500000
        small  5.500000  8.500000
    foo large  2.000000  4.500000
        small  2.333333  4.333333

    We can also calculate multiple types of aggregations for any given
    value column.

    >>> table = pd.pivot_table(df, values=['D', 'E'], index=['A', 'C'],
    ...                        aggfunc={'D': "mean",
    ...                                 'E': ["min", "max", "mean"]})
    >>> table
                      D   E
                   mean max      mean  min
    A   C
    bar large  5.500000   9  7.500000    6
        small  5.500000   9  8.500000    8
    foo large  2.000000   5  4.500000    4
        small  2.333333   6  4.333333    2

In [11]:
import pandas as pd

# Create the dataset
data = {
    "Province": ["Addis Ababa", "Addis Ababa", "Addis Ababa", "Oromia", "Oromia", "Oromia",
                 "Tigray", "Tigray", "Tigray", "Amhara", "Amhara", "Amhara"],
    "VehicleType": ["Car", "Car", "Bike", "Car", "Car", "Bike",
                    "Car", "Car", "Bike", "Car", "Bike", "Bike"],
    "Gender": ["F", "M", "F", "F", "M", "M", "F", "M", "F", "F", "M", "F"],
    "ClaimAmount": [5000, 7000, 1200, 4500, 4800, 1000, 5500, 6000, 1300, 4900, 1100, 1000],
    "Premium": [800, 950, 200, 850, 870, 150, 900, 920, 220, 870, 180, 160],
    "Year": [2023, 2023, 2023, 2023, 2023, 2023, 2022, 2022, 2022, 2022, 2022, 2022],
    "PolicyType": ["Full", "Full", "Partial", "Full", "Partial", "Partial",
                   "Full", "Partial", "Partial", "Full", "Partial", "Partial"]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print("Original Dataset:")
print(df)

Original Dataset:
       Province VehicleType Gender  ClaimAmount  Premium  Year PolicyType
0   Addis Ababa         Car      F         5000      800  2023       Full
1   Addis Ababa         Car      M         7000      950  2023       Full
2   Addis Ababa        Bike      F         1200      200  2023    Partial
3        Oromia         Car      F         4500      850  2023       Full
4        Oromia         Car      M         4800      870  2023    Partial
5        Oromia        Bike      M         1000      150  2023    Partial
6        Tigray         Car      F         5500      900  2022       Full
7        Tigray         Car      M         6000      920  2022    Partial
8        Tigray        Bike      F         1300      220  2022    Partial
9        Amhara         Car      F         4900      870  2022       Full
10       Amhara        Bike      M         1100      180  2022    Partial
11       Amhara        Bike      F         1000      160  2022    Partial

lets practice the question we have got 
Beginner Level

Compute the average ClaimAmount per Province.
Compute the total Premium per Province.
Count the number of policies per Province.
Compute the average ClaimAmount per VehicleType.
Find the maximum Premium per Gender.

🔹 Intermediate Level

Compute the average ClaimAmount per Province and VehicleType.
Compute the total Premium per Province and VehicleType.
Compute the average ClaimAmount per Province split by Gender.
Compute the sum of Premium per Province split by Gender.
Count the number of policies per Province and PolicyType.

🔹 Advanced Level (Multi-level Pivot)

Compute the average ClaimAmount and Premium per Province & VehicleType, split by Gender.
Compute ClaimAmount (mean) and Premium (sum) per Province & VehicleType, split by Gender.
Include totals (margins=True) for the above pivot table.
Replace missing values with 0 in the pivot table above.
Create a pivot table with multi-level aggregation:
ClaimAmount → mean, max
Premium → sum, min
Rows → Province + VehicleType
Columns → Gender

🔹 Expert / Challenge Level

Compute the average ClaimAmount per Year and Province, split by Gender, include totals.
Compute the total Premium per Year, Province, VehicleType, and split by PolicyType.
Identify Province and VehicleType combinations with no policies for a Gender, using fill_value=0.
Flatten the multi-level column pivot table into single-level columns for ML preprocessing.
Using the same dataset, create a 3D pivot table:
Index → Province + VehicleType
Columns → Year + Gender
Values → ClaimAmount and Premium
Aggregations → mean for ClaimAmount, sum for Premium

In [12]:
df

       Province VehicleType Gender  ClaimAmount  Premium  Year PolicyType
0   Addis Ababa         Car      F         5000      800  2023       Full
1   Addis Ababa         Car      M         7000      950  2023       Full
2   Addis Ababa        Bike      F         1200      200  2023    Partial
3        Oromia         Car      F         4500      850  2023       Full
4        Oromia         Car      M         4800      870  2023    Partial
5        Oromia        Bike      M         1000      150  2023    Partial
6        Tigray         Car      F         5500      900  2022       Full
7        Tigray         Car      M         6000      920  2022    Partial
8        Tigray        Bike      F         1300      220  2022    Partial
9        Amhara         Car      F         4900      870  2022       Full
10       Amhara        Bike      M         1100      180  2022    Partial
11       Amhara        Bike      F         1000      160  2022    Partial

beginner questions

In [25]:
# 1. Compute the average ClaimAmount per Province.
ans1 = pd.pivot_table(df , index= 'Province',values='ClaimAmount',aggfunc ='mean')
ans1

# 2.Compute the total Premium per Province.
ans2 = pd.pivot_table(df , index= 'Province' , values= 'Premium' , aggfunc= 'sum')
ans2

# 3. Count the number of policies per Province.
ans3 = pd.pivot_table(df, values= 'PolicyType', index= 'Province' , aggfunc= 'count')
ans3 

# 4. Compute the average ClaimAmount per VehicleType.
ans4 = pd.pivot_table(df , values= 'ClaimAmount' , index= 'VehicleType' , aggfunc= 'mean' )
ans4 

# 5. Find the maximum Premium per Gender.
ans5 = pd.pivot_table(df , values= 'Premium' , index = 'Gender' , aggfunc= 'max' )
ans5

        Premium
Gender
F           900
M           950

In [29]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Province     12 non-null     object
 1   VehicleType  12 non-null     object
 2   Gender       12 non-null     object
 3   ClaimAmount  12 non-null     int64
 4   Premium      12 non-null     int64
 5   Year         12 non-null     int64
 6   PolicyType   12 non-null     object
dtypes: int64(3), object(4)
memory usage: 804.0+ bytes

In [37]:
#  1. Compute the average ClaimAmount per Province and VehicleType.

ans1 = pd.pivot_table(df , index= ['Province' , 'VehicleType'] , values = 'ClaimAmount' , aggfunc= 'mean' )
ans1 

# 2. Compute the total Premium per Province and VehicleType.
ans2 = pd.pivot_table(df , index= ['Province' , 'VehicleType'] , values = 'Premium' , aggfunc= 'sum' )
ans2

# 3. Compute the average ClaimAmount per Province split by Gender.
ans3 = pd.pivot_table(df , index= ['Province'] , columns= 'Gender' , values = 'ClaimAmount' , aggfunc= 'mean' )
ans3

# 4. Compute the sum of Premium per Province split by Gender.
ans4 = pd.pivot_table(df , index= ['Province'] , columns= 'Gender' , values = 'Premium' , aggfunc= 'sum' )
ans4

# 5. Count the number of policies per Province and PolicyType.
ans5 = pd.pivot_table(df , index= ['Province', 'PolicyType']   , aggfunc= 'size' )
ans5

Province     PolicyType
Addis Ababa  Full          2
             Partial       1
Amhara       Full          1
             Partial       2
Oromia       Full          1
             Partial       2
Tigray       Full          1
             Partial       2
dtype: int64

In [ ]:
# 1. Compute the average ClaimAmount and Premium per Province & VehicleType, split by Gender.
ans1 = pd.pivot_table(df , values= ['ClaimAmount' ,'Premium'] , index= ['Province' ,'VehicleType' ] ,columns= 'Gender' , aggfunc= 'mean' )
ans1

#2. Compute ClaimAmount (mean) and Premium (sum) per Province & VehicleType, split by Gender.
ans2 = pd.pivot_table(df , values= ['ClaimAmount' ,'Premium'] , index= ['Province' ,'VehicleType' ] ,columns= 'Gender' , aggfunc= {'ClaimAmount':'mean' , 'Premium':'sum'} )
ans2

# 3. Include totals (margins=True) for the above pivot table.
ans3 = pd.pivot_table(df , values= ['ClaimAmount' ,'Premium'] , index= ['Province' ,'VehicleType' ] ,columns= 'Gender' , margins= True, aggfunc= {'ClaimAmount':'mean' , 'Premium':'sum'} )
ans3

# 4. Replace missing values with 0 in the pivot table above.
ans4 = pd.pivot_table(df , values= ['ClaimAmount' ,'Premium'] , index= ['Province' ,'VehicleType' ] ,fill_value= 0,columns= 'Gender' , margins= True, aggfunc= {'ClaimAmount':'mean' , 'Premium':'sum'} )
ans4

# 5. 
'''
Create a pivot table with multi-level aggregation:
ClaimAmount → mean, max
Premium → sum, min
Rows → Province + VehicleType
Columns → Gender'''
ans5 = pd.pivot_table(df , index= ['Province' ,'VehicleType'] , values= ['ClaimAmount' ,'Premium' ] ,fill_value= 0,columns= 'Gender' , aggfunc= {'ClaimAmount':['mean' , 'max'], 'Premium':['sum', 'min']} )
ans5

                        ClaimAmount                       Premium            \
                                max          mean             min       sum
Gender                            F     M       F       M       F    M    F
Province    VehicleType
Addis Ababa Bike               1200     0  1200.0     0.0     200    0  200
            Car                5000  7000  5000.0  7000.0     800  950  800
Amhara      Bike               1000  1100  1000.0  1100.0     160  180  160
            Car                4900     0  4900.0     0.0     870    0  870
Oromia      Bike                  0  1000     0.0  1000.0       0  150    0
            Car                4500  4800  4500.0  4800.0     850  870  850
Tigray      Bike               1300     0  1300.0     0.0     220    0  220
            Car                5500  6000  5500.0  6000.0     900  920  900



Gender                     M
Province    VehicleType
Addis Ababa Bike           0
            Car          950
Amhara      Bike         180
            Car            0
Oromia      Bike         150
            Car          870
Tigray      Bike           0
            Car          920

In [49]:
df.columns

Index(['Province', 'VehicleType', 'Gender', 'ClaimAmount', 'Premium', 'Year',
       'PolicyType'],
      dtype='object')

In [ ]:
# 1. Compute the average ClaimAmount per Year and Province, split by Gender, include totals.
ans1 = pd.pivot_table(df , index= ['Year','Province'],columns= 'Gender',margins= True,values='ClaimAmount',aggfunc='mean' )
ans1

# 2. Compute the total Premium per Year, Province, VehicleType, and split by PolicyType.
ans2 = pd.pivot_table(df , values= 'Premium' ,index= ['Year', 'Province', 'VehicleType'] , aggfunc= 'sum', columns= 'Gender')
ans2

# 3. Identify Province and VehicleType combinations with no policies for a Gender, using fill_value=0.
ans3 = pd.pivot_table(df , index= ['Province' , 'VehicleType'] , columns= 'Gender' ,fill_value=0 , values= 'PolicyType' , aggfunc= 'count' )
no_pol = ans3[(ans3==0).any(axis=1)]
no_pol

Gender                   F  M
Province    VehicleType
Addis Ababa Bike         1  0
Amhara      Car          1  0
Oromia      Bike         0  1
Tigray      Bike         1  0

In [ ]:
'''
| Function   | Description                                                 |
| ---------- | ----------------------------------------------------------- |
| `'sum'`    | Sum of all values in the group                              |
| `'mean'`   | Average (arithmetic mean)                                   |
| `'median'` | Median value                                                |
| `'min'`    | Minimum value                                               |
| `'max'`    | Maximum value                                               |
| `'count'`  | Number of non-NA values                                     |
| `'size'`   | Number of rows in the group (including NA if `values=None`) |
| `'std'`    | Standard deviation                                          |
| `'var'`    | Variance                                                    |
| `'first'`  | First value in the group                                    |
| `'last'`   | Last value in the group                                     |
| `'prod'`   | Product of all values                                       |
'''

''