mean imputations:Replace missing values with the average of the column.

In [2]:
import pandas as pd 
df = pd.DataFrame({'name':[1,2,3,45]})

In [3]:
help(df.fillna)

Help on method fillna in module pandas.core.generic:

fillna(
    value: 'Hashable | Mapping | Series | DataFrame | None' = None,
    *,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool_t' = False,
    limit: 'int | None' = None,
    downcast: 'dict | None | lib.NoDefault' = <no_default>
) -> 'Self | None' method of pandas.core.frame.DataFrame instance
    Fill NA/NaN values using the specified method.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    method : {'backfill', 'bfill', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series:

        * ffill: propagate last valid observation forward to next valid.
        * backfill / bfill: use next valid observation to fill gap.

        .. deprecated:: 2.1.0
            Use ffill or bfill instead.

    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        If method is specified, this is the maximum number of consecutive
        NaN values to forward/backward fill. In other words, if there is
        a gap with more than this number of consecutive NaNs, it will only
        be partially filled. If method is not specified, this is the
        maximum number of entries along the entire axis where NaNs will be
        filled. Must be greater than 0 if not None.
    downcast : dict, default is None
        A dict of item->dtype of what to downcast if possible,
        or the string 'infer' which will try to downcast to an appropriate
        equal type (e.g. float64 to int64 if possible).

        .. deprecated:: 2.2.0

    Returns
    -------
    Series/DataFrame or None
        Object with missing values filled or None if ``inplace=True``.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Examples
    --------
    >>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
    ...                    [3, 4, np.nan, 1],
    ...                    [np.nan, np.nan, np.nan, np.nan],
    ...                    [np.nan, 3, np.nan, 4]],
    ...                   columns=list("ABCD"))
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [4]:
import pandas as pd
import numpy as np

# Create a sample dataset
data = {
    'Age': [25, np.nan, 30, 22, np.nan, 28],
    'Salary': [5000, 6000, np.nan, 4500, 7000, np.nan],
    'Gender': ['Male', 'Female', np.nan, 'Male', 'Female', np.nan],
    'City': ['NY', np.nan, 'LA', 'NY', np.nan, 'Chicago']
}

df = pd.DataFrame(data)
print("Original Dataset:")
print(df)

Original Dataset:
    Age  Salary  Gender     City
0  25.0  5000.0    Male       NY
1   NaN  6000.0  Female      NaN
2  30.0     NaN     NaN       LA
3  22.0  4500.0    Male       NY
4   NaN  7000.0  Female      NaN
5  28.0     NaN     NaN  Chicago

In [9]:
# filling null values with the mean 
df['Age'] = df['Age'].astype('Int64')
print(df.dtypes)
df.isnull().sum()

Age         Int64
Salary    float64
Gender     object
City       object
dtype: object

Age       2
Salary    2
Gender    2
City      2
dtype: int64

In [ ]:
df['Age'] = df['Age'].fillna(int(df['Age'].mean()))
df

   Age  Salary  Gender     City
0   25  5000.0    Male       NY
1   26  6000.0  Female      NaN
2   30     NaN     NaN       LA
3   22  4500.0    Male       NY
4   26  7000.0  Female      NaN
5   28     NaN     NaN  Chicago

In [13]:
help(df.select_dtypes)

Help on method select_dtypes in module pandas.core.frame:

select_dtypes(include=None, exclude=None) -> 'Self' method of pandas.core.frame.DataFrame instance
    Return a subset of the DataFrame's columns based on the column dtypes.

    Parameters
    ----------
    include, exclude : scalar or list-like
        A selection of dtypes or strings to be included/excluded. At least
        one of these parameters must be supplied.

    Returns
    -------
    DataFrame
        The subset of the frame including the dtypes in ``include`` and
        excluding the dtypes in ``exclude``.

    Raises
    ------
    ValueError
        * If both of ``include`` and ``exclude`` are empty
        * If ``include`` and ``exclude`` have overlapping elements
        * If any kind of string dtype is passed in.

    See Also
    --------
    DataFrame.dtypes: Return Series with the data type of each column.

    Notes
    -----
    * To select all *numeric* types, use ``np.number`` or ``'number'``
    * To select strings you must use the ``object`` dtype, but note that
      this will return *all* object dtype columns. With
      ``pd.options.future.infer_string`` enabled, using ``"str"`` will
      work to select all string columns.
    * See the `numpy dtype hierarchy
      <https://numpy.org/doc/stable/reference/arrays.scalars.html>`__
    * To select datetimes, use ``np.datetime64``, ``'datetime'`` or
      ``'datetime64'``
    * To select timedeltas, use ``np.timedelta64``, ``'timedelta'`` or
      ``'timedelta64'``
    * To select Pandas categorical dtypes, use ``'category'``
    * To select Pandas datetimetz dtypes, use ``'datetimetz'``
      or ``'datetime64[ns, tz]'``

    Examples
    --------
    >>> df = pd.DataFrame({'a': [1, 2] * 3,
    ...                    'b': [True, False] * 3,
    ...                    'c': [1.0, 2.0] * 3})
    >>> df
            a      b  c
    0       1   True  1.0
    1       2  False  2.0
    2       1   True  1.0
    3       2  False  2.0
    4       1   True  1.0
    5       2  False  2.0

    >>> df.select_dtypes(include='bool')
       b
    0  True
    1  False
    2  True
    3  False
    4  True
    5  False

    >>> df.select_dtypes(include=['float64'])
       c
    0  1.0
    1  2.0
    2  1.0
    3  2.0
    4  1.0
    5  2.0

    >>> df.select_dtypes(exclude=['int64'])
           b    c
    0   True  1.0
    1  False  2.0
    2   True  1.0
    3  False  2.0
    4   True  1.0
    5  False  2.0

In [18]:
# when to use mean is when the data type is numerical
df.info()
num_col = df.select_dtypes(include=['Int64' ,'float64'])
print(num_col)
 
# Now imputations with the mean 

for col in num_col:
    df[col] = df[col].fillna(df[col].mean())

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     6 non-null      Int64
 1   Salary  6 non-null      float64
 2   Gender  4 non-null      object
 3   City    4 non-null      object
dtypes: Int64(1), float64(1), object(2)
memory usage: 330.0+ bytes
   Age  Salary
0   25  5000.0
1   26  6000.0
2   30  5625.0
3   22  4500.0
4   26  7000.0
5   28  5625.0

   Age  Salary  Gender     City
0   25  5000.0    Male       NY
1   26  6000.0  Female      NaN
2   30  5625.0     NaN       LA
3   22  4500.0    Male       NY
4   26  7000.0  Female      NaN
5   28  5625.0     NaN  Chicago