In [24]:
import pandas as pd
import numpy as np

# Create a sample dataset
data = {
    'Age': [25, np.nan, 30, 22, np.nan, 28],
    'Salary': [5000, 6000, np.nan, 4500, 7000, np.nan],
    'Gender': ['Male', 'Female', np.nan, 'Male', 'Female', np.nan],
    'City': ['NY', np.nan, 'LA', 'NY', np.nan, 'Chicago']
}

df = pd.DataFrame(data)
print("Original Dataset:")
print(df)

Original Dataset:
    Age  Salary  Gender     City
0  25.0  5000.0    Male       NY
1   NaN  6000.0  Female      NaN
2  30.0     NaN     NaN       LA
3  22.0  4500.0    Male       NY
4   NaN  7000.0  Female      NaN
5  28.0     NaN     NaN  Chicago

In [25]:
df['Gender'] = df['Gender'].astype('category')

In [ ]:
# fill the categorical cols with the most frequent values

cat_cols = df.select_dtypes(include=['object','category'])
for col in cat_cols:
    mode_cols = df[col].mode() # when the elements of the columns has eqaul number 
    df[col] = df[col].fillna(mode_cols[0])

df

    Age  Salary  Gender     City
0  25.0  5000.0    Male       NY
1   NaN  6000.0  Female       NY
2  30.0     NaN  Female       LA
3  22.0  4500.0    Male       NY
4   NaN  7000.0  Female       NY
5  28.0     NaN  Female  Chicago

In [34]:
# when the frequency is equal we can use random again 

import random

cat_cols = df.select_dtypes(include= ['object','category'])
for col in cat_cols:
    mode_cols = df[col].mode()
    df[col] = df[col].fillna(random.choice(mode_cols))

df

    Age  Salary  Gender     City
0  25.0  5000.0    Male       NY
1   NaN  6000.0  Female       NY
2  30.0     NaN  Female       LA
3  22.0  4500.0    Male       NY
4   NaN  7000.0  Female       NY
5  28.0     NaN  Female  Chicago