In [147]:
import pandas as pd

In [148]:
df = pd.read_csv("../../data/practicebothcatandnumudingdesiciontree.csv")

In [149]:
df

,Experience,Salary,Rating,Department,Gender,Education,Position,Age,Tenure,Region
0,2.0,40000.0,3.8,IT,M,Masters,Engineer,25,2,North
1,5.0,55000.0,4.5,HR,F,Bachelor,Manager,30,5,South
2,7.0,70000.0,4.9,IT,M,Masters,Senior Engineer,35,7,East
3,3.0,45000.0,4.0,Sales,F,Bachelor,Executive,28,3,West
4,NaN,48000.0,4.2,IT,M,PhD,Engineer,26,2,North
5,10.0,90000.0,5.0,Marketing,F,Masters,Director,40,10,South
6,4.0,50000.0,NaN,Sales,M,Bachelor,Executive,27,4,East
7,6.0,NaN,4.3,HR,F,Masters,Manager,32,6,West
8,NaN,42000.0,3.9,NaN,M,Bachelor,Analyst,24,1,North
9,8.0,80000.0,4.8,Marketing,F,Masters,Senior Manager,38,8,South
10,3.0,43000.0,3.7,Sales,M,Bachelor,Executive,29,3,East
11,5.0,60000.0,4.6,HR,F,Masters,Manager,31,5,West
12,2.0,41000.0,NaN,IT,M,Bachelor,Engineer,25,2,North
13,7.0,72000.0,4.7,Sales,F,Masters,Senior Engineer,36,7,South
14,NaN,50000.0,4.1,Marketing,M,PhD,Analyst,27,3,East
15,4.0,52000.0,4.4,HR,F,Masters,Manager,30,4,West
16,6.0,65000.0,4.5,IT,M,Masters,Senior Engineer,34,6,North
17,5.0,58000.0,NaN,Sales,F,Bachelor,Executive,29,5,South
18,NaN,49000.0,4.0,Marketing,M,Masters,Analyst,26,2,East
19,9.0,85000.0,4.9,IT,F,PhD,Director,39,9,West

In [150]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Experience  16 non-null     float64
 1   Salary      19 non-null     float64
 2   Rating      17 non-null     float64
 3   Department  19 non-null     object
 4   Gender      20 non-null     object
 5   Education   20 non-null     object
 6   Position    20 non-null     object
 7   Age         20 non-null     int64
 8   Tenure      20 non-null     int64
 9   Region      20 non-null     object
dtypes: float64(3), int64(2), object(5)
memory usage: 1.7+ KB

In [151]:
df.isnull().sum()

Experience    4
Salary        1
Rating        3
Department    1
Gender        0
Education     0
Position      0
Age           0
Tenure        0
Region        0
dtype: int64

In [152]:
cat_cols = df.select_dtypes(include='object')

In [153]:
cat_cols_encoded = pd.get_dummies(cat_cols.drop('Department' ,axis=1)).astype(int)

In [154]:
cat_cols_encoded['Department'] = cat_cols['Department']

In [155]:
num_cols = df.select_dtypes(include='number')

In [156]:
df_cat_train  = pd.concat([num_cols , cat_cols_encoded] , axis= 1)

In [157]:
df_cat_train

,Experience,Salary,Rating,Age,Tenure,Gender_F,Gender_M,Education_Bachelor,Education_Masters,Education_PhD,...,Position_Engineer,Position_Executive,Position_Manager,Position_Senior Engineer,Position_Senior Manager,Region_East,Region_North,Region_South,Region_West,Department
0,2.0,40000.0,3.8,25,2,0,1,0,1,0,...,1,0,0,0,0,0,1,0,0,IT
1,5.0,55000.0,4.5,30,5,1,0,1,0,0,...,0,0,1,0,0,0,0,1,0,HR
2,7.0,70000.0,4.9,35,7,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,IT
3,3.0,45000.0,4.0,28,3,1,0,1,0,0,...,0,1,0,0,0,0,0,0,1,Sales
4,NaN,48000.0,4.2,26,2,0,1,0,0,1,...,1,0,0,0,0,0,1,0,0,IT
5,10.0,90000.0,5.0,40,10,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,Marketing
6,4.0,50000.0,NaN,27,4,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,Sales
7,6.0,NaN,4.3,32,6,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
8,NaN,42000.0,3.9,24,1,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,NaN
9,8.0,80000.0,4.8,38,8,1,0,0,1,0,...,0,0,0,0,1,0,0,1,0,Marketing
10,3.0,43000.0,3.7,29,3,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,Sales
11,5.0,60000.0,4.6,31,5,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
12,2.0,41000.0,NaN,25,2,0,1,1,0,0,...,1,0,0,0,0,0,1,0,0,IT
13,7.0,72000.0,4.7,36,7,1,0,0,1,0,...,0,0,0,1,0,0,0,1,0,Sales
14,NaN,50000.0,4.1,27,3,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,Marketing
15,4.0,52000.0,4.4,30,4,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
16,6.0,65000.0,4.5,34,6,0,1,0,1,0,...,0,0,0,1,0,0,1,0,0,IT
17,5.0,58000.0,NaN,29,5,1,0,1,0,0,...,0,1,0,0,0,0,0,1,0,Sales
18,NaN,49000.0,4.0,26,2,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,Marketing
19,9.0,85000.0,4.9,39,9,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,IT

In [158]:
cat_cols = pd.get_dummies(cat_cols).astype(int)
df = pd.concat([num_cols , cat_cols] , axis=1)
df

,Experience,Salary,Rating,Age,Tenure,Department_HR,Department_IT,Department_Marketing,Department_Sales,Gender_F,...,Position_Director,Position_Engineer,Position_Executive,Position_Manager,Position_Senior Engineer,Position_Senior Manager,Region_East,Region_North,Region_South,Region_West
0,2.0,40000.0,3.8,25,2,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,5.0,55000.0,4.5,30,5,1,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
2,7.0,70000.0,4.9,35,7,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,3.0,45000.0,4.0,28,3,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,1
4,NaN,48000.0,4.2,26,2,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
5,10.0,90000.0,5.0,40,10,0,0,1,0,1,...,1,0,0,0,0,0,0,0,1,0
6,4.0,50000.0,NaN,27,4,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
7,6.0,NaN,4.3,32,6,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
8,NaN,42000.0,3.9,24,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,8.0,80000.0,4.8,38,8,0,0,1,0,1,...,0,0,0,0,0,1,0,0,1,0
10,3.0,43000.0,3.7,29,3,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
11,5.0,60000.0,4.6,31,5,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
12,2.0,41000.0,NaN,25,2,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
13,7.0,72000.0,4.7,36,7,0,0,0,1,1,...,0,0,0,0,1,0,0,0,1,0
14,NaN,50000.0,4.1,27,3,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
15,4.0,52000.0,4.4,30,4,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
16,6.0,65000.0,4.5,34,6,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
17,5.0,58000.0,NaN,29,5,0,0,0,1,1,...,0,0,1,0,0,0,0,0,1,0
18,NaN,49000.0,4.0,26,2,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
19,9.0,85000.0,4.9,39,9,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [159]:
df.isnull().sum()

Experience                  4
Salary                      1
Rating                      3
Age                         0
Tenure                      0
Department_HR               0
Department_IT               0
Department_Marketing        0
Department_Sales            0
Gender_F                    0
Gender_M                    0
Education_Bachelor          0
Education_Masters           0
Education_PhD               0
Position_Analyst            0
Position_Director           0
Position_Engineer           0
Position_Executive          0
Position_Manager            0
Position_Senior Engineer    0
Position_Senior Manager     0
Region_East                 0
Region_North                0
Region_South                0
Region_West                 0
dtype: int64

In [160]:
# imputation for numerical values 

missing_cols = ['Experience','Salary' ,'Rating']

for col in missing_cols:
    complete_data = df[df[col].notnull()]
    incomplete_data = df[df[col].isnull()]

    x_train = complete_data.drop(col , axis=1)
    y_train = complete_data[col]

    from sklearn.tree import DecisionTreeRegressor
    model = DecisionTreeRegressor()
    model.fit(x_train , y_train)

    predict = model.predict(incomplete_data.drop(col , axis=1))
    df.loc[df[col].isnull(), col] = predict

In [161]:
df

,Experience,Salary,Rating,Age,Tenure,Department_HR,Department_IT,Department_Marketing,Department_Sales,Gender_F,...,Position_Director,Position_Engineer,Position_Executive,Position_Manager,Position_Senior Engineer,Position_Senior Manager,Region_East,Region_North,Region_South,Region_West
0,2.0,40000.0,3.8,25,2,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
1,5.0,55000.0,4.5,30,5,1,0,0,0,1,...,0,0,0,1,0,0,0,0,1,0
2,7.0,70000.0,4.9,35,7,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,3.0,45000.0,4.0,28,3,0,0,0,1,1,...,0,0,1,0,0,0,0,0,0,1
4,4.0,48000.0,4.2,26,2,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
5,10.0,90000.0,5.0,40,10,0,0,1,0,1,...,1,0,0,0,0,0,0,0,1,0
6,4.0,50000.0,4.0,27,4,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
7,6.0,65000.0,4.3,32,6,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
8,2.0,42000.0,3.9,24,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,8.0,80000.0,4.8,38,8,0,0,1,0,1,...,0,0,0,0,0,1,0,0,1,0
10,3.0,43000.0,3.7,29,3,0,0,0,1,0,...,0,0,1,0,0,0,1,0,0,0
11,5.0,60000.0,4.6,31,5,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
12,2.0,41000.0,3.8,25,2,0,1,0,0,0,...,0,1,0,0,0,0,0,1,0,0
13,7.0,72000.0,4.7,36,7,0,0,0,1,1,...,0,0,0,0,1,0,0,0,1,0
14,4.0,50000.0,4.1,27,3,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
15,4.0,52000.0,4.4,30,4,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,1
16,6.0,65000.0,4.5,34,6,0,1,0,0,0,...,0,0,0,0,1,0,0,1,0,0
17,5.0,58000.0,4.0,29,5,0,0,0,1,1,...,0,0,1,0,0,0,0,0,1,0
18,4.0,49000.0,4.0,26,2,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
19,9.0,85000.0,4.9,39,9,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,1

In [162]:
df.isnull().sum()

Experience                  0
Salary                      0
Rating                      0
Age                         0
Tenure                      0
Department_HR               0
Department_IT               0
Department_Marketing        0
Department_Sales            0
Gender_F                    0
Gender_M                    0
Education_Bachelor          0
Education_Masters           0
Education_PhD               0
Position_Analyst            0
Position_Director           0
Position_Engineer           0
Position_Executive          0
Position_Manager            0
Position_Senior Engineer    0
Position_Senior Manager     0
Region_East                 0
Region_North                0
Region_South                0
Region_West                 0
dtype: int64

In [163]:
df_check =df_cat_train.drop(['Experience' ,'Salary' ,'Rating'] , axis= 1)
df_check
columns_not_drop = ['Experience' ,'Salary' ,'Rating']
df = df.drop(columns= [c for c in df.columns if c not in columns_not_drop])
df

df = pd.concat([df  , df_check ] ,axis=1)
df

,Experience,Salary,Rating,Age,Tenure,Gender_F,Gender_M,Education_Bachelor,Education_Masters,Education_PhD,...,Position_Engineer,Position_Executive,Position_Manager,Position_Senior Engineer,Position_Senior Manager,Region_East,Region_North,Region_South,Region_West,Department
0,2.0,40000.0,3.8,25,2,0,1,0,1,0,...,1,0,0,0,0,0,1,0,0,IT
1,5.0,55000.0,4.5,30,5,1,0,1,0,0,...,0,0,1,0,0,0,0,1,0,HR
2,7.0,70000.0,4.9,35,7,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,IT
3,3.0,45000.0,4.0,28,3,1,0,1,0,0,...,0,1,0,0,0,0,0,0,1,Sales
4,4.0,48000.0,4.2,26,2,0,1,0,0,1,...,1,0,0,0,0,0,1,0,0,IT
5,10.0,90000.0,5.0,40,10,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,Marketing
6,4.0,50000.0,4.0,27,4,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,Sales
7,6.0,65000.0,4.3,32,6,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
8,2.0,42000.0,3.9,24,1,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,NaN
9,8.0,80000.0,4.8,38,8,1,0,0,1,0,...,0,0,0,0,1,0,0,1,0,Marketing
10,3.0,43000.0,3.7,29,3,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,Sales
11,5.0,60000.0,4.6,31,5,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
12,2.0,41000.0,3.8,25,2,0,1,1,0,0,...,1,0,0,0,0,0,1,0,0,IT
13,7.0,72000.0,4.7,36,7,1,0,0,1,0,...,0,0,0,1,0,0,0,1,0,Sales
14,4.0,50000.0,4.1,27,3,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,Marketing
15,4.0,52000.0,4.4,30,4,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
16,6.0,65000.0,4.5,34,6,0,1,0,1,0,...,0,0,0,1,0,0,1,0,0,IT
17,5.0,58000.0,4.0,29,5,1,0,1,0,0,...,0,1,0,0,0,0,0,1,0,Sales
18,4.0,49000.0,4.0,26,2,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,Marketing
19,9.0,85000.0,4.9,39,9,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,IT

In [164]:
df.isnull().sum()

Experience                  0
Salary                      0
Rating                      0
Age                         0
Tenure                      0
Gender_F                    0
Gender_M                    0
Education_Bachelor          0
Education_Masters           0
Education_PhD               0
Position_Analyst            0
Position_Director           0
Position_Engineer           0
Position_Executive          0
Position_Manager            0
Position_Senior Engineer    0
Position_Senior Manager     0
Region_East                 0
Region_North                0
Region_South                0
Region_West                 0
Department                  1
dtype: int64

In [165]:
# for Categorical imputation of departement 
complete_cat = df[df['Department'].notnull()]
incomplete_cat = df[df['Department'].isnull()]

x_train = complete_cat.drop('Department' , axis=1)
y_train = complete_cat['Department']

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train , y_train)

predict = model.predict(incomplete_cat.drop('Department' , axis= 1))

df.loc[df['Department'].isnull() , 'Department'] = predict

df

,Experience,Salary,Rating,Age,Tenure,Gender_F,Gender_M,Education_Bachelor,Education_Masters,Education_PhD,...,Position_Engineer,Position_Executive,Position_Manager,Position_Senior Engineer,Position_Senior Manager,Region_East,Region_North,Region_South,Region_West,Department
0,2.0,40000.0,3.8,25,2,0,1,0,1,0,...,1,0,0,0,0,0,1,0,0,IT
1,5.0,55000.0,4.5,30,5,1,0,1,0,0,...,0,0,1,0,0,0,0,1,0,HR
2,7.0,70000.0,4.9,35,7,0,1,0,1,0,...,0,0,0,1,0,1,0,0,0,IT
3,3.0,45000.0,4.0,28,3,1,0,1,0,0,...,0,1,0,0,0,0,0,0,1,Sales
4,4.0,48000.0,4.2,26,2,0,1,0,0,1,...,1,0,0,0,0,0,1,0,0,IT
5,10.0,90000.0,5.0,40,10,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,Marketing
6,4.0,50000.0,4.0,27,4,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,Sales
7,6.0,65000.0,4.3,32,6,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
8,2.0,42000.0,3.9,24,1,0,1,1,0,0,...,0,0,0,0,0,0,1,0,0,IT
9,8.0,80000.0,4.8,38,8,1,0,0,1,0,...,0,0,0,0,1,0,0,1,0,Marketing
10,3.0,43000.0,3.7,29,3,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,Sales
11,5.0,60000.0,4.6,31,5,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
12,2.0,41000.0,3.8,25,2,0,1,1,0,0,...,1,0,0,0,0,0,1,0,0,IT
13,7.0,72000.0,4.7,36,7,1,0,0,1,0,...,0,0,0,1,0,0,0,1,0,Sales
14,4.0,50000.0,4.1,27,3,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,Marketing
15,4.0,52000.0,4.4,30,4,1,0,0,1,0,...,0,0,1,0,0,0,0,0,1,HR
16,6.0,65000.0,4.5,34,6,0,1,0,1,0,...,0,0,0,1,0,0,1,0,0,IT
17,5.0,58000.0,4.0,29,5,1,0,1,0,0,...,0,1,0,0,0,0,0,1,0,Sales
18,4.0,49000.0,4.0,26,2,0,1,0,1,0,...,0,0,0,0,0,1,0,0,0,Marketing
19,9.0,85000.0,4.9,39,9,1,0,0,0,1,...,0,0,0,0,0,0,0,0,1,IT

In [166]:
df.isnull().sum()

Experience                  0
Salary                      0
Rating                      0
Age                         0
Tenure                      0
Gender_F                    0
Gender_M                    0
Education_Bachelor          0
Education_Masters           0
Education_PhD               0
Position_Analyst            0
Position_Director           0
Position_Engineer           0
Position_Executive          0
Position_Manager            0
Position_Senior Engineer    0
Position_Senior Manager     0
Region_East                 0
Region_North                0
Region_South                0
Region_West                 0
Department                  0
dtype: int64

In [167]:
df.columns

Index(['Experience', 'Salary', 'Rating', 'Age', 'Tenure', 'Gender_F',
       'Gender_M', 'Education_Bachelor', 'Education_Masters', 'Education_PhD',
       'Position_Analyst', 'Position_Director', 'Position_Engineer',
       'Position_Executive', 'Position_Manager', 'Position_Senior Engineer',
       'Position_Senior Manager', 'Region_East', 'Region_North',
       'Region_South', 'Region_West', 'Department'],
      dtype='object')

In [168]:
df.columns

Index(['Experience', 'Salary', 'Rating', 'Age', 'Tenure', 'Gender_F',
       'Gender_M', 'Education_Bachelor', 'Education_Masters', 'Education_PhD',
       'Position_Analyst', 'Position_Director', 'Position_Engineer',
       'Position_Executive', 'Position_Manager', 'Position_Senior Engineer',
       'Position_Senior Manager', 'Region_East', 'Region_North',
       'Region_South', 'Region_West', 'Department'],
      dtype='object')

In [169]:
df['Gender'] = df[['Gender_F' , 'Gender_M']].idxmax(axis=1)
df['Gender'] = df['Gender'].str.replace('Gender_' ,'')
df['Education'] = df[['Education_Bachelor','Education_Masters','Education_PhD']].idxmax(axis=1)
df['Education'] = df['Education'].str.replace('Education_','')
df['Position'] = df[['Position_Analyst', 'Position_Director', 'Position_Engineer',
       'Position_Executive', 'Position_Manager', 'Position_Senior Engineer',
       'Position_Senior Manager']].idxmax(axis=1)
df['Position'] = df['Position'].str.replace('Position_','')
df['Region'] = df[[ 'Region_East', 'Region_North',
       'Region_South', 'Region_West']].idxmax(axis=1)

df['Region'] = df['Region'].str.replace('Region_' ,'')

general_cols = ['Experience', 'Salary', 'Rating', 'Age', 'Tenure','Department', 'Gender', 'Education',
       'Position', 'Region']

df = df.drop(columns =[c for c in df.columns if c not in general_cols] , axis=1)

In [170]:
df

,Experience,Salary,Rating,Age,Tenure,Department,Gender,Education,Position,Region
0,2.0,40000.0,3.8,25,2,IT,M,Masters,Engineer,North
1,5.0,55000.0,4.5,30,5,HR,F,Bachelor,Manager,South
2,7.0,70000.0,4.9,35,7,IT,M,Masters,Senior Engineer,East
3,3.0,45000.0,4.0,28,3,Sales,F,Bachelor,Executive,West
4,4.0,48000.0,4.2,26,2,IT,M,PhD,Engineer,North
5,10.0,90000.0,5.0,40,10,Marketing,F,Masters,Director,South
6,4.0,50000.0,4.0,27,4,Sales,M,Bachelor,Executive,East
7,6.0,65000.0,4.3,32,6,HR,F,Masters,Manager,West
8,2.0,42000.0,3.9,24,1,IT,M,Bachelor,Analyst,North
9,8.0,80000.0,4.8,38,8,Marketing,F,Masters,Senior Manager,South
10,3.0,43000.0,3.7,29,3,Sales,M,Bachelor,Executive,East
11,5.0,60000.0,4.6,31,5,HR,F,Masters,Manager,West
12,2.0,41000.0,3.8,25,2,IT,M,Bachelor,Engineer,North
13,7.0,72000.0,4.7,36,7,Sales,F,Masters,Senior Engineer,South
14,4.0,50000.0,4.1,27,3,Marketing,M,PhD,Analyst,East
15,4.0,52000.0,4.4,30,4,HR,F,Masters,Manager,West
16,6.0,65000.0,4.5,34,6,IT,M,Masters,Senior Engineer,North
17,5.0,58000.0,4.0,29,5,Sales,F,Bachelor,Executive,South
18,4.0,49000.0,4.0,26,2,Marketing,M,Masters,Analyst,East
19,9.0,85000.0,4.9,39,9,IT,F,PhD,Director,West