In [42]:
import pandas as pd
import numpy as np 

df = pd.DataFrame({
    'Age': [25, 30, 35 ,25],
    'Gender': ['M', 'F', 'M','M'],
    'Income': [50000, np.nan, 70000, np.nan]
})

In [43]:
df

   Age Gender   Income
0   25      M  50000.0
1   30      F      NaN
2   35      M  70000.0
3   25      M      NaN

In [44]:
df[df['Income'].isnull()]

   Age Gender  Income
1   30      F     NaN
3   25      M     NaN

In [ ]:
# hot Deck is used for the imuting missing value having the same other columns 
# for example in index =3 the age and gender of missing value is the same as index 1 
# age = 25 ,gender = m 
# so hot impuation can work 
for idx , row in df[df['Income'].isnull()].iterrows():
    donor = df[(df['Age'] == row['Age']) & (df['Gender'] == row['Gender']) & df['Income'].notnull()]
    if not donor.empty:
        df.loc[idx ,'Income'] = donor['Income'].sample(n=1, random_state=42).values[0]
    else:
        df.loc[idx , 'Income'] = df['Income'].median()
        # here for female who has 30 there is no such donor that is why we filled with the median 
df

   Age Gender   Income
0   25      M  50000.0
1   30      F  60000.0
2   35      M  70000.0
3   25      M  50000.0